jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'PDUtil.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'My executable'
          options: