  - name: Versatile PyInstaller
  # You may pin to the exact commit or the version.
  # uses: sayyid5416/pyinstaller@454cc5f88cbfd6a1f7f5e6b9b96a0216be7f1720
  uses: sayyid5416/pyinstaller@v1.3.0
  with:
    # path of your '.py' or '.spec' file. 
    spec: 'PDUtil.spec'
    # path of your requirements.txt file
    requirements: 'requirements.txt'
    # Options to set for pyinstaller command Ex: options: '--onedir, -F'       (seperated by comma and space)
    options: # optional, default is 
    # specific python version you want to use
    python_ver: # optional, default is 3.10
    # specific python architecture you want to use
    python_arch: # optional, default is x64
    # Path on runner-os, where generated executable files are stored
    exe_path: # optional, default is ./dist
    # If passed, uploads executable artifact  with this name. Else, artifact won't be uploaded.
    upload_exe_with_name: # optional, default is 
